### PR TITLE
update wikipedia-api dependency to use Tokenizer interface

### PR DESCRIPTION
**Pull request by mssammon**
-- see branch 'ms' of wikipedia-api, which is based on multilingual branch of https://gitlab-beta.engr.illinois.edu/cogcomp/wikipedia-api

This change seems to cause Chinese wikification to FAIL (tokenization seems fine but links are all NIL, no idea why) -- would appreciate help figuring out what is going on here.

Also: missing indexes now cause exceptions to be thrown and System.exit() to be called, rather than simply logging an error and failing later.

### CODE REVIEW

**Comment by mssammon** [comment]
This fork now also creates Constituents with all targets plus scores for which an English wikipedia target can be found.

**Comment by cttsai** [comment]
I just checked the Chinese issue. It turns out that the CharacterTokenizer doesn't normalize Chinese characters to simplified Chinese. Since everything should be in simplified Chinese, mentions in traditional Chinese may get no title candidate. (The test case is in traditional Chinese)

The strange thing is that I saw you did this conversion in 
https://gitlab-beta.engr.illinois.edu/cogcomp/wikipedia-api/blob/ms/src/main/java/edu/illinois/cs/cogcomp/tokenizers/CharacterTokenizer.java 

Any idea why it doesn't work?

**Comment by mssammon** [comment]
It looks to me like I'm doing things correctly at least within wikipedia-api, but the client needs to do the normalization first, before calling TextAnnotationBuilder. https://github.com/IllinoisCogComp/illinois-cogcomp-nlp/blob/master/tokenizer/src/main/java/edu/illinois/cs/cogcomp/nlp/utility/TokenizerTextAnnotationBuilder.java
-- this uses the original text as the reference text it stores, and just uses the offsets produced by the Tokenizer.  I don't think this is a bug, just the way it works.  
BTW how do you display Chinese characters in Intellij/on your terminal? One reason I couldn't identify this problem is that I couldn't see the characters, just empty boxes -- or I might have noticed the surface forms were different between versions of the code...

**Comment by mssammon** [comment]
I have added a test that illustrates a problem I'm having when I try to use SurfaceCluster.NilClustering() in my own code -- the mentions don't appear to get clustered across documents.  Can you take a look and let me know how to do this correctly?

**Comment by mssammon** [comment]
OK ignore my previous comment -- I can see now that I was mis-specifying a threshold value for clustering.

**Comment by cttsai** [comment]
Thanks. I've made it normalize Chinese text before making TextAnnotation. 

After updating Intellij, Chinese characters are all empty boxes for me as well....haven't found a way solve this yet.  But I have no problem of showing Chinese in terminal. I guess it's because of locale? Mine is en_US.UTF-8.

**Pull request merged**
